version: '3.9'
services:
  amqp:
    container_name: "amqp"
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=firstrabbit
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq